name: mactest
description: Flutter Mac Test
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  logging: 0.11.3+2
  flutter_secure_storage: ^3.3.1+1
  intl: ^0.16.0
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  jaguar_jwt: ^2.1.6
  webview_flutter: ^0.3.18+1
  slider_button: ^0.3.0
  flutter_masked_text: ^0.8.0
  flutter_webview_plugin: ^0.3.10
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
